import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>next-todo-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet"></link>
      </Head>
      <div>
        <h1>Hello world!</h1>
      </div>
    </div>
  );
}
